PROGRAMS += curl_lib_test


CURL_TEST_BUILD = $(BUILD_DIR)/curl_lib_test


# CURL files generated by BUILD_CURL.
CURL_TEST_INSTALL = \
	src/external/curl/Linux
	#$(CURL_TEST_BUILD)/curl/install

CURL_TEST_LIBRARY = \
	$(CURL_TEST_INSTALL)/lib/libcurl.a

CURL_TEST_CONFIG = \
	$(CURL_TEST_INSTALL)/bin/curl-config


# Allow curl_lib_test.cpp to include:
#   #include <curl/curl.h>
CURL_CPPFLAGS_CURL_TEST = \
	-I$(CURL_TEST_INSTALL)/include


# Static CURL applications on Windows must define CURL_STATICLIB.
ifeq ($(PLATFORM),WINDOWS)
	CURL_CPPFLAGS_CURL_TEST += -DCURL_STATICLIB
endif


CPPFLAGS_CURL_TEST = \
	$(CURL_CPPFLAGS_CURL_TEST)
	# ADD HERE OTHER FLAG IF NEEDED

# COMMON OBJECTS
CURL_TEST_OBJ = \
	$(CURL_TEST_BUILD)/test_curl_lib.o


# Generate the static libcurl build rule.
#
# runs `define BUILD_CURL` macro from curl.mk and replaces $(1) with $(CURL_TEST_BUILD)
# `$(eval ...)` takes the generated Makefile code and adds it to the
#     current Makefile, as if you had written it yourself..
#$(eval $(call BUILD_CURL,$(CURL_TEST_BUILD)))


# Create objects from C++ sources
$(CURL_TEST_BUILD)/%.o: src/unit_test/%.cpp  | $(CURL_TEST_LIBRARY)
	@mkdir -p $(@D)
	$(CXX) -c $< $(CPPFLAGS_CURL_TEST) $(CXXFLAGS) -o $@


# Build the final executable with all object
#
# curl-config --static-libs returns libcurl and the other
# libraries required by the selected CURL configuration.
curl_lib_test: $(CURL_TEST_OBJ)
ifeq ($(PLATFORM),WINDOWS)
	$(CXX) $(LDFLAGS) $(CURL_TEST_OBJ) $$("$(CURL_TEST_CONFIG)" --static-libs) $(LDLIBS) -o $@.exe
else ifeq ($(PLATFORM),MAC)
	$(CXX) $(LDFLAGS) $(CURL_TEST_OBJ) $$("$(CURL_TEST_CONFIG)" --static-libs) $(LDLIBS) -o $@
else
	$(CXX) $(LDFLAGS) $(CURL_TEST_OBJ) $$("$(CURL_TEST_CONFIG)" --static-libs) $(LDLIBS) -o $@
endif


$(info CURL_TEST_BUILD=$(CURL_TEST_BUILD))
$(info CURL_TEST_OBJ=$(CURL_TEST_OBJ))
$(info SRC=$(wildcard src/unit_test/*.cpp))


