name: CMake Cross-Platform Test

on:
  push:
  pull_request:

env:
  PROGRAMS: "clock_update"
  #PROGRAMS: "clock_update weather_update picture_upload"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}


    # https://github.com/actions/runner-images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install deps
    - name: Install libusb (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev

    # Build
    - name: Configure CMake
      run: cmake -S . -B cmake-build

    - name: Build (Linux/macOS)
      if: runner.os != 'Windows'
      run: cmake --build cmake-build

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake --build cmake-build
        foreach ($exe in $env:PROGRAMS.Split(' ')) {
          $src = "cmake-build\Debug\${exe}.exe"
          $dst = "cmake-build\${exe}.exe"
          if (Test-Path $src) {
            Write-Host "Moving ${exe}"
            Move-Item -Path $src -Destination $dst
          }
          else {
            Write-Host "Executable not found: ${src}"
            Write-Host "Contents of cmake-build:"
            Get-ChildItem -Recurse cmake-build
            exit 1
          }
        }

    # Execute (|| true to prevent the program fail if no HID device is connected)
    - name: Run executable (Linux/MacOS)
      if: runner.os != 'Windows'
      run: |
        for bin in $PROGRAMS; do
          echo "Running $bin"
          ./cmake-build/$bin || true
        done

    - name: Run executable (Windows)
      if: runner.os == 'Windows'
      run: |
        foreach ($exe in $env:PROGRAMS.Split(' ')) {
          Write-Host "Running ${exe}"
          if (Test-Path ".\cmake-build\${exe}.exe") {
            & ".\cmake-build\${exe}.exe"
            exit 0
          }
          else {
            Write-Host "Executable not found!"
            Get-ChildItem .\cmake-build -Recurse
          }
        }
        exit 1

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: CHILKEY_ND104_Multitool-CMAKE-${{ runner.os }}
        path: |
          cmake-build/clock_update*
          #cmake-build/weather_update*
          #cmake-build/picture_upload*
          clock_update*
          #weather_update*
          #picture_upload*
