name: Makefile Cross-Platform Test

on:
  push:
  pull_request:

env:
  PROGRAMS: "clock_update"
  #PROGRAMS: "clock_update weather_update picture_upload"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}


    # https://github.com/actions/runner-images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install deps
    - name: Install MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        install: make gcc

    - name: Install libusb (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev

    # Build
    - name: Build (Linux/macOS)
      if: runner.os != 'Windows'
      run: make

    - name: Build (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: make

    # Execute (|| true to prevent the program fail if no HID device is connected)
    - name: Run executable (Linux/MacOS)
      if: runner.os != 'Windows'
      run: |
        for bin in $PROGRAMS; do
          echo "Running $bin"
          ./$bin || true
        done

    - name: Run executable (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        for exe in $PROGRAMS; do
          echo "Running $exe"
          if [[ -f "./$exe.exe" ]]; then
            "./$exe.exe" || true
            exit 0
          else
            echo "Executable not found!"
            find .
          fi
        done
        exit 1

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: CHILKEY_ND104_Multitool-MAKE-${{ runner.os }}
        path: |
          build/clock_update*
          #build/weather_update*
          #build/picture_upload*
          clock_update*
          #weather_update*
          #picture_upload*

